version: '3'
services:
  server:
    build:
      context: .
      dockerfile: backend
    container_name: backend
    network_mode: host
    depends_on:
      - redis
    command: flask run -p 8080
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data